[package]
name = "voters"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
diesel = {version = "2.0", featues = ["postgres"]}
serde = {version = "2.0", features = ["derive"]}
serde_json = "1.0"
uuid = "1.0"
dotenv = "0.15"
tera = "1.13"
rand = "0.8"
